### ISSUE TITLE
Sponsor link seems to be wrong

### ISSUE THREAD

**Issue by isidorn** [cedric05/dothttp-runner#106]
Open your extension in VS Code, click on Sponsor button. It takes the user to https://github.com/sponsors/nvaccess
Instead you should put your sponsorship link instead. Thanks!

**Comment by cedric05** [comment]
fixed via https://github.com/cedric05/dothttp-runner/commit/7b8bc3120786b3dec716ca2159f4f3c872934894
Thanks @isidorn
